version: '3.6'

services:

  url-shorter.nginx:
    build:
      context: ./nginx
    image: url-shorter.nginx:dev
    container_name: url-shorter.nginx
    env_file:
      - .env
    ports:
      - "${HOST_NGINX_PORT}:80"
    links:
      - url-shorter.php
    volumes:
      - ../public:/var/www/url-shorter/public
    networks:
      - url_shorter_network

  url-shorter.php:
    build:
      context: ./php
    image: url-shorter.php:dev
    container_name: url-shorter.php
    env_file:
      - .env
    expose:
      - 9000
    volumes:
      - ../:/var/www/url-shorter:rw
    networks:
      - url_shorter_network

  url-shorter.db:
    image: "postgres:14"
    container_name: url-shorter.db
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - ./var/db-data:/var/lib/postgresql/data:rw
    networks:
      - url_shorter_network

volumes:
  db-data:

networks:
  url_shorter_network:
    driver: bridge