parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Migrations/'
            - '../src/ConstantBag/'
            - '../src/Dto/'

    App\Services\Link\LinkService:
        arguments:
            - '@App\Repository\Link\LinkRepository'

    App\EventListener\ApiContentTypeEventListener:
        tags:
            - { name: kernel.event_listener }