parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{Kernel.php, ConstantBag, Dto, Entity, Migrations, tests}'

    App\Repository\Link\LinkRepositoryInterface: 'App\Repository\Link\LinkRepository'

    App\Services\Link\LinkService:
        arguments:
            - '@App\Repository\Link\LinkRepository'

    App\Persistence\Generator\LinkGenerator: ~

    App\EventListener\ApiContentTypeEventListener:
        tags:
            - { name: kernel.event_listener }